INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'sonia@gmail.com', 'sonia@123', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'abc@gmail.com', 'abc@789', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'priya@gmail.com', 'priya', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'sajith@gmail.com', 'sajith@123', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'pqr@gmail.com', 'pqr@123', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'admin', 'admin', 'ADMIN');